// renderer/components/PresentationDialog.tsx
import {
  KeyboardEvent,
  useCallback,
  useEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
} from 'react'
import fileUrl from 'file-url'
import {
  AppBar,
  Box,
  Dialog,
  Fade,
  IconButton,
  LinearProgress,
  Slider,
  Toolbar,
  Typography,
} from '@mui/material'
import {
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Close as CloseIcon,
} from '@mui/icons-material'
import Layout from 'components/Layout'
import { useTheme } from 'contexts/ThemeContext'
import { File } from 'interfaces'
import { useAppSelector } from 'store'
import { selectFullscreen } from 'store/settings'
import { isImageFile } from 'utils/image'

type State = { images: File[]; index: number; loading: boolean }

type Action =
  | { type: 'loaded'; payload: { images: File[]; index: number } }
  | { type: 'loading' }
  | { type: 'moveNext' }
  | { type: 'movePrevious' }
  | { type: 'moveTo'; payload: number }
  | { type: 'reset' }

const reducer = (state: State, action: Action) => {
  switch (action.type) {
    case 'loaded':
      return {
        ...state,
        images: action.payload.images,
        index: action.payload.index,
        loading: false,
      }
    case 'loading':
      return { ...state, images: [], index: 0, loading: true }
    case 'moveNext': {
      let index = state.index + 1
      if (index > state.images.length - 1) {
        index = 0
      }
      return { ...state, index }
    }
    case 'movePrevious': {
      let index = state.index - 1
      if (index < 0) {
        index = state.images.length - 1
      }
      return { ...state, index }
    }
    case 'moveTo':
      return { ...state, index: action.payload }
    case 'reset':
      return { images: [], index: 0, loading: false }
    default:
      return state
  }
}

type Props = {
  onRequestClose: () => void
  open: boolean
  path: string
}

const PresentationDialog = (props: Props) => {
  const { path, onRequestClose, open } = props

  const { forceMode, resetMode } = useTheme()

  const fullscreen = useAppSelector(selectFullscreen)

  const [{ images, index, loading }, dispatch] = useReducer(reducer, {
    images: [],
    index: 0,
    loading: false,
  })
  const [toolbar, setToolbar] = useState(false)
  const timer = useRef<number>()
  const topToolbar = useRef<HTMLDivElement>(null)
  const bottomToolbar = useRef<HTMLDivElement>(null)

  const clearTimer = useCallback(() => window.clearTimeout(timer.current), [])

  const resetTimer = useCallback(() => {
    setToolbar(true)
    clearTimer()
    const hovered =
      !!topToolbar.current?.querySelector(':hover') ||
      !!bottomToolbar.current?.querySelector(':hover')
    if (hovered) {
      return
    }
    timer.current = window.setTimeout(() => setToolbar(false), 2000)
  }, [clearTimer])

  useEffect(() => {
    const handleFullscreenChange = () =>
      !document.fullscreenElement && onRequestClose()
    document.body.addEventListener('fullscreenchange', handleFullscreenChange)
    return () => {
      document.body.removeEventListener(
        'fullscreenchange',
        handleFullscreenChange
      )
    }
  }, [onRequestClose])

  useEffect(() => {
    ;(async () => {
      if (open) {
        dispatch({ type: 'loading' })
        fullscreen && (await document.body.requestFullscreen())
        forceMode('dark')
        resetTimer()
        let files: File[] = []
        try {
          files = await window.electronAPI.listFilesWithPath(path)
        } catch (e) {
          // noop
        }
        const images = files.filter((file) => isImageFile(file.path))
        const index = Math.max(
          0,
          images.findIndex((image) => image.path === path)
        )
        dispatch({ type: 'loaded', payload: { images, index } })
      } else {
        dispatch({ type: 'reset' })
        clearTimer()
        resetMode()
        document.fullscreenElement && (await document.exitFullscreen())
      }
    })()
  }, [clearTimer, forceMode, open, path, resetMode, resetTimer])

  const image = useMemo(() => images[index], [images, index])

  const movePrevious = () => dispatch({ type: 'movePrevious' })

  const moveNext = () => dispatch({ type: 'moveNext' })

  const handleKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    switch (e.key) {
      case 'ArrowLeft':
      case 'ArrowUp':
        return movePrevious()
      case 'ArrowRight':
      case 'ArrowDown':
        return moveNext()
      case 'Tab':
        return resetTimer()
    }
  }

  const handleMouseMove = () => resetTimer()

  const handleClickPrevious = () => movePrevious()

  const handleClickNext = () => moveNext()

  const handleChange = (_e: Event, value: number | number[]) => {
    if (!Array.isArray(value)) {
      dispatch({ type: 'moveTo', payload: value })
    }
  }

  return (
    <Dialog
      fullScreen
      onClose={onRequestClose}
      onKeyDown={handleKeyDown}
      onMouseMove={handleMouseMove}
      open={open}
      sx={{ cursor: toolbar ? undefined : 'none' }}
      transitionDuration={0}
    >
      <Layout dialog>
        <Fade in={toolbar}>
          <AppBar color="transparent" elevation={0}>
            <Box
              sx={{
                background:
                  'linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0))',
                pb: 15,
              }}
            >
              <Toolbar ref={topToolbar} variant="dense">
                <IconButton
                  color="inherit"
                  edge="start"
                  onClick={onRequestClose}
                >
                  <CloseIcon />
                </IconButton>
                {image && (
                  <Typography
                    component="div"
                    sx={{ ml: 2, flex: 1 }}
                    variant="subtitle1"
                  >
                    {image.name}
                  </Typography>
                )}
              </Toolbar>
            </Box>
          </AppBar>
        </Fade>
        {loading && (
          <Box sx={{ position: 'absolute', top: 0, width: '100%' }}>
            <LinearProgress />
          </Box>
        )}
        {image && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={fileUrl(image.path)}
            style={{
              display: 'block',
              height: '100%',
              objectFit: 'scale-down',
              width: '100%',
            }}
          />
        )}
        <Fade in={toolbar}>
          <AppBar
            color="transparent"
            component="footer"
            elevation={0}
            sx={{ top: 'auto', bottom: 0 }}
          >
            <Box
              sx={{
                background:
                  'linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5))',
                pt: 15,
              }}
            >
              <Toolbar ref={bottomToolbar} variant="dense">
                <Slider
                  max={images.length - 1}
                  min={0}
                  onChange={handleChange}
                  size="small"
                  sx={{
                    position: 'absolute',
                    left: 0,
                    lineHeight: 0,
                    top: -14,
                    width: '100%',
                    zIndex: (theme) => theme.zIndex.appBar + 1,
                  }}
                  value={index}
                />
                <IconButton
                  color="inherit"
                  edge="start"
                  onClick={handleClickPrevious}
                >
                  <ChevronLeftIcon />
                </IconButton>
                <IconButton color="inherit" onClick={handleClickNext}>
                  <ChevronRightIcon />
                </IconButton>
                <Typography component="div" sx={{ ml: 1 }} variant="body1">
                  {index + 1} / {images.length}
                </Typography>
              </Toolbar>
            </Box>
          </AppBar>
        </Fade>
      </Layout>
    </Dialog>
  )
}

export default PresentationDialog

// src/components/PresentationDialog.vue
<template>
  <v-dialog
    ref="dialog"
    v-model="state.active"
    class="presentation-dialog"
    content-class="presentation-dialog-content"
    fullscreen
    hide-overlay
    eager
    :transition="false"
  >
    <v-card
      :class="classes"
      dark
      flat
      tile
      class="d-flex flex-column fill-height"
    >
      <title-bar :app="false" />
      <div class="wrapper fill-height">
        <presentation-content
          class="fill-height"
          :loading="state.loading"
          :scale="state.scale"
          :file="state.current"
          @change:zoom="handleChangeZoom"
        />
        <div class="top-overlay d-flex pb-15">
          <presentation-top-toolbar
            ref="topToolbar"
            :file="state.current"
            @click:close="handleClickClose"
          />
        </div>
        <div class="bottom-overlay d-flex pt-15">
          <presentation-bottom-toolbar
            ref="bottomToolbar"
            :page="page"
            :max-page="maxPage"
            :scale="state.scale"
            :full-screen="state.fullScreen"
            @click:previous="handleClickPrevious"
            @click:next="handleClickNext"
            @click:zoom-in="handleClickZoomIn"
            @click:zoom-out="handleClickZoomOut"
            @click:zoom-reset="handleClickZoomReset"
            @click:toggle-full-screen="handleClickToggleFullScreen"
            @change:page="handleChangePage"
          />
        </div>
      </div>
    </v-card>
  </v-dialog>
</template>

<script lang="ts">
import {
  defineComponent,
  computed,
  reactive,
  watch,
  ref,
  onMounted,
  SetupContext,
  onUnmounted,
} from 'nuxt-composition-api'
import { promisify } from '@fiahfy/worker-promisify'
import PresentationBottomToolbar from '~/components/PresentationBottomToolbar.vue'
import PresentationTopToolbar from '~/components/PresentationTopToolbar.vue'
import { File } from '~/models'
import { settingsStore } from '~/store'

// eslint-disable-next-line @typescript-eslint/no-var-requires
const Worker = require('~/workers/fetch-files.worker')

const worker = promisify(new Worker())

const scales = [
  0.25,
  0.33,
  0.5,
  0.67,
  0.75,
  0.8,
  0.9,
  1,
  1.1,
  1.25,
  1.5,
  1.75,
  2,
  2.5,
  3,
  4,
  5,
]

export default defineComponent({
  setup(_props: unknown, context: SetupContext) {
    const state = reactive<{
      active: boolean
      loading: boolean
      error?: Error
      files: File[]
      current?: File
      target?: File
      toolbar?: boolean
      timer?: number
      scale: number
      originalScale: number
      fullScreen: boolean
    }>({
      active: false,
      loading: false,
      error: undefined,
      files: [],
      current: undefined,
      target: undefined,
      toolbar: undefined,
      timer: undefined,
      scale: 1,
      originalScale: 1,
      fullScreen: false,
    })

    const classes = computed(() => {
      return {
        'toolbar-hidden': state.toolbar === false,
        'toolbar-fade-in': state.toolbar === true,
        'toolbar-fade-out': state.toolbar === false,
      }
    })
    const page = computed(
      () =>
        state.files.findIndex((file) => file.path === state.current?.path) + 1
    )
    const maxPage = computed(() => state.files.length)

    const dialog = ref<Vue>()
    const topToolbar = ref<InstanceType<typeof PresentationTopToolbar>>()
    const bottomToolbar = ref<InstanceType<typeof PresentationBottomToolbar>>()

    const showPresentation = async (file: File) => {
      state.active = true
      state.target = file
      if (settingsStore.fullScreen) {
        dialog.value && (await dialog.value?.$el.requestFullscreen())
      }
      load()
    }
    const hidePresentation = async () => {
      document.fullscreenElement && (await document.exitFullscreen())
      state.current = undefined
      state.active = false
    }
    const clearTimer = () => {
      window.clearTimeout(state.timer)
    }
    const setTimer = () => {
      state.timer = window.setTimeout(() => {
        state.toolbar = false
        bottomToolbar.value && bottomToolbar.value.hideMenu()
      }, 2000)
    }
    const resetTimer = () => {
      clearTimer()
      if (topToolbar.value?.isHover() || bottomToolbar.value?.isHover()) {
        return
      }
      setTimer()
    }
    const showToolbar = () => {
      if (state.toolbar === false) {
        state.toolbar = true
      }
      resetTimer()
    }
    const load = async () => {
      if (state.loading || !state.target) {
        return
      }
      state.loading = true
      state.files = []
      state.current = undefined
      state.error = undefined
      try {
        let files = []
        if (state.target.directory) {
          const { data }: { data: File[] } = await worker.postMessage({
            dirPath: state.target.path,
            recursive: settingsStore.recursive,
          })
          files = data
        } else {
          const { data }: { data: File[] } = await worker.postMessage({
            dirPath: state.target.parent,
          })
          files = data
          state.current = state.target
        }
        state.files = files.filter((file) =>
          settingsStore.isFileAvailable(file.path)
        )
        if (!state.current) {
          state.current = state.files[0]
        }
      } catch (e) {
        state.error = e
      }
      state.loading = false
    }
    const movePrevious = () => {
      let newPage = page.value - 1
      if (newPage < 1) {
        newPage = maxPage.value
      }
      state.current = state.files[newPage - 1]
    }
    const movekNext = () => {
      let newPage = page.value + 1
      if (newPage > maxPage.value) {
        newPage = 1
      }
      state.current = state.files[newPage - 1]
    }

    const handleFullScreenChange = () => {
      state.fullScreen = !!document.fullscreenElement
    }
    const handleKeyDown = (e: KeyboardEvent) => {
      switch (e.key) {
        case 'Escape':
          e.preventDefault()
          return hidePresentation()
        case 'ArrowLeft':
        case 'ArrowUp':
          e.preventDefault()
          return movePrevious()
        case 'ArrowRight':
        case 'ArrowDown':
          e.preventDefault()
          return movekNext()
      }
    }
    const handleMouseMove = () => {
      showToolbar()
    }
    const handleClickClose = () => {
      hidePresentation()
    }
    const handleClickPrevious = () => {
      movePrevious()
    }
    const handleClickNext = () => {
      movekNext()
    }
    const handleClickZoomIn = () => {
      state.scale = scales.find((scale) => scale > state.scale) ?? state.scale
    }
    const handleClickZoomOut = () => {
      state.scale =
        scales
          .concat()
          .reverse()
          .find((scale) => scale < state.scale) ?? state.scale
    }
    const handleClickZoomReset = () => {
      state.scale = state.originalScale
    }
    const handleClickToggleFullScreen = async () => {
      if (state.fullScreen) {
        await document.exitFullscreen()
      } else {
        dialog.value && (await dialog.value?.$el.requestFullscreen())
      }
    }
    const handleChangePage = (page: number) => {
      if (page < 1 || page > maxPage.value) {
        return
      }
      state.current = state.files[page - 1]
    }
    const handleChangeZoom = (scale: number) => {
      state.scale = scale
      state.originalScale = scale
    }

    onMounted(() => {
      document.body.addEventListener('keydown', handleKeyDown)
      document.body.addEventListener('fullscreenchange', handleFullScreenChange)
      context.root.$eventBus.$on('show-presentation', showPresentation)
      context.root.$eventBus.$on('hide-resentation', hidePresentation)
    })

    onUnmounted(() => {
      document.body.removeEventListener('keydown', handleKeyDown)
      document.body.removeEventListener(
        'fullscreenchange',
        handleFullScreenChange
      )
      context.root.$eventBus.$off('show-presentation', showPresentation)
      context.root.$eventBus.$off('hide-presentation', hidePresentation)
    })

    watch(
      () => state.active,
      (active) => {
        if (active) {
          showToolbar()
          document.body.addEventListener('mousemove', handleMouseMove)
          context.root.$nextTick(() => {
            const content = document.querySelector(
              '.presentation-dialog-content'
            )
            if (content?.parentElement instanceof HTMLElement) {
              content.parentElement.focus()
            }
          })
        } else {
          state.toolbar = undefined
          clearTimer()
          document.body.removeEventListener('mousemove', handleMouseMove)
          context.root.$eventBus.$emit('focus-explorer')
        }
      }
    )

    return {
      state,
      classes,
      page,
      maxPage,
      dialog,
      topToolbar,
      bottomToolbar,
      handleClickClose,
      handleClickPrevious,
      handleClickNext,
      handleClickZoomIn,
      handleClickZoomOut,
      handleClickZoomReset,
      handleClickToggleFullScreen,
      handleChangePage,
      handleChangeZoom,
    }
  },
})
</script>

<style lang="scss" scoped>
@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@keyframes fade-out {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}

.v-card {
  &.toolbar-hidden {
    .presentation-content {
      cursor: none;
    }
  }
  &.toolbar-fade-in {
    .top-overlay,
    .bottom-overlay {
      animation: fade-in 0.3s forwards;
    }
  }
  &.toolbar-fade-out {
    .top-overlay,
    .bottom-overlay {
      animation: fade-out 0.3s forwards;
    }
  }
  > .wrapper {
    position: relative;
    > .top-overlay {
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0));
      left: 0;
      position: absolute;
      right: 0;
      top: 0;
    }
    > .bottom-overlay {
      background: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5));
      bottom: 0;
      left: 0;
      position: absolute;
      right: 0;
    }
  }
}
</style>
