// renderer/components/TitleBar.tsx
import { AppBar, Toolbar, Typography } from '@mui/material'
import { useEffect, useState } from 'react'

const TitleBar = () => {
  const [fullScreen, setFullScreen] = useState(false)

  const handleFullScreenChange = () => {
    setFullScreen(!!document.fullscreenElement)
  }

  useEffect(() => {
    document.body.addEventListener('fullscreenchange', handleFullScreenChange)
    return () => {
      document.body.removeEventListener(
        'fullscreenchange',
        handleFullScreenChange
      )
    }
  }, [])

  // @see https://github.com/electron/electron/issues/16385
  const handleDoubleClick = () => {
    // const doubleClickAction = systemPreferences.getUserDefault(
    //   'AppleActionOnDoubleClick',
    //   'string'
    // )
    // const win = getCurrentWindow()
    // if (doubleClickAction === 'Minimize') {
    //   win.minimize()
    // } else if (doubleClickAction === 'Maximize') {
    //   if (win.isMaximized()) {
    //     win.unmaximize()
    //   } else {
    //     win.maximize()
    //   }
    // }
  }

  return (
    !fullScreen && (
      <AppBar
        elevation={0}
        onDoubleClick={handleDoubleClick}
        position="fixed"
        sx={{
          WebkitAppRegion: 'drag',
          userSelect: 'none',
          zIndex: (theme) => theme.zIndex.drawer + 1,
        }}
      >
        <Toolbar
          sx={{
            justifyContent: 'center',
          }}
        >
          <Typography align="center" component="div" noWrap variant="caption">
            Clipped drawer
          </Typography>
        </Toolbar>
      </AppBar>
    )
  )
}

export default TitleBar

// src/components/TitleBar.vue
<template>
  <v-system-bar
    v-if="titleBar"
    class="title-bar user-select-none"
    :app="app"
    height="22"
    @dblclick="handleDoubleClick"
  >
    <v-spacer />
    <span class="caption text-truncate">Picty</span>
    <v-spacer />
  </v-system-bar>
</template>

<script lang="ts">
import { getCurrentWindow, systemPreferences } from '@electron/remote'
import {
  defineComponent,
  reactive,
  computed,
  onMounted,
  onUnmounted,
} from '@nuxtjs/composition-api'

export default defineComponent({
  props: {
    app: {
      type: Boolean,
      default: true,
    },
  },
  setup() {
    const state = reactive({
      fullScreen: false,
    })

    const titleBar = computed(() => {
      return process.platform === 'darwin' && !state.fullScreen
    })

    // @see https://github.com/electron/electron/issues/16385
    const handleDoubleClick = () => {
      const doubleClickAction = systemPreferences.getUserDefault(
        'AppleActionOnDoubleClick',
        'string'
      )
      const win = getCurrentWindow()
      if (doubleClickAction === 'Minimize') {
        win.minimize()
      } else if (doubleClickAction === 'Maximize') {
        if (win.isMaximized()) {
          win.unmaximize()
        } else {
          win.maximize()
        }
      }
    }
    const handleFullScreenChange = () => {
      state.fullScreen = !!document.fullscreenElement
    }

    onMounted(() => {
      document.body.addEventListener('fullscreenchange', handleFullScreenChange)
    })

    onUnmounted(() => {
      document.body.removeEventListener(
        'fullscreenchange',
        handleFullScreenChange
      )
    })

    return {
      titleBar,
      handleDoubleClick,
    }
  },
})
</script>

<style lang="scss" scoped>
.title-bar {
  padding: 0 72px;
  -webkit-app-region: drag;
}
</style>
